#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Time-Period
Version  : 1.25
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/P/PB/PBOYD/Time-Period-1.25.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PB/PBOYD/Time-Period-1.25.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtime-period-perl/libtime-period-perl_1.25-1.debian.tar.xz
Summary  : 'A Perl module to deal with time periods.'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Time-Period-man

%description
This Perl module uses the conditions given by Perl.  This module may only
be distributed and or modified under the conditions given by Perl.

%package man
Summary: man components for the perl-Time-Period package.
Group: Default

%description man
man components for the perl-Time-Period package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Time-Period-1.25
mkdir -p %{_topdir}/BUILD/Time-Period-1.25/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Time-Period-1.25/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Time/Period.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Time::Period.3
